version: '3'
services:
  db_spineanalyzer:
    image: mariadb:10.2
    container_name: db_spineanalyzer
    restart: unless-stopped
    environment:
      MYSQL_USER: teamanubot
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_DATABASE: spineanalyzer
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro

  fastapi-app:
    build: .
    container_name: fastapi-app
    restart: unless-stopped
    environment:
      MYSQL_USER: teamanubot
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_DATABASE: spineanalyzer
      MYSQL_HOST: db_spineanalyzer
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"
    working_dir: /app
    depends_on:
      - db_spineanalyzer