name: spineanalyzer
version: 1.0.0+1
description: A Flutter app for spine analysis and admin management.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.2
  path: ^1.8.3
  shared_preferences: ^2.2.2

  image: ^4.1.7
  fl_chart: ^1.1.1

  image_picker: ^1.0.7
  intl: ^0.20.2
  http: ^1.2.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # - assets/logo.png
    # Add other asset files as needed
